PLOVER_VERSION_PREFIX="4.0.0.dev8"
PLOVER_VERSION_POSTFIX="66.g685bd33"
PLOVER_VERSION_DOT="${PLOVER_VERSION_PREFIX}.${PLOVER_VERSION_POSTFIX}"
PLOVER_VERSION_PLUS="${PLOVER_VERSION_PREFIX}+${PLOVER_VERSION_POSTFIX}"
PLOVER_APPIMAGE_NAME="plover-${PLOVER_VERSION_DOT}-x86_64.AppImage"

PLOVER_URL="https://github.com/openstenoproject/plover/releases/download/weekly-v${PLOVER_VERSION_PLUS}/${PLOVER_APPIMAGE_NAME}"

echo downloading plover from $PLOVER_URL
curl -sSL "$PLOVER_URL" > "/tmp/${PLOVER_APPIMAGE_NAME}"
chmod uga+x /tmp/${PLOVER_APPIMAGE_NAME}
/tmp/${PLOVER_APPIMAGE_NAME} --install
rm "/tmp/${PLOVER_APPIMAGE_NAME}"
