#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# If we have homebrew, let's install and setup homebrew.
if test $(which brew)
then
    # Run Homebrew through the Brewfile
    echo "› brew bundle"
    brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
